config/routes.rb
Rails.application.routes.draw do

  resources :pages
  # resource :service_spare, only: [:show] do
  get '/service_spare/:id', to: 'service_spare#show', as: 'service_spare'
  # end

  get 'search', to: 'search#index'

  get 'search/show', to: 'searche#show'

  resources :news_items
  resources :contacts

  get '/service/:id', to: 'service#show', as: 'service'

  get 'home/index'

  resources :categories, only: [:show], shallow: true do
    resources :products, only: [:show]
  end

  mount Ckeditor::Engine => '/ckeditor'
  root to: 'home#index'

  devise_for :users, controllers: { registrations: "registrations" }

  mount Uploader::Engine => '/uploader'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routinrdmg.html
  # root to: 'home@index'
end

app/views/shared/_footer.html.erb
<div class="ui footer segment">
   <div class="ui container">
      <div class="ui stackable column grid" id="footer-grid">
         <div class="column four wide computer footer-address">
            <div class="ui header">Центральный офис
               в Санкт-Петербурге:
            </div>
            <div class="content">
               Витебский пр. 31 корпус 2 литер 1.
            </div>
         </div>
         <div class="column four wide computer footer-address">
            <div class="ui header">Филиал в Москве</div>
            <div class="content">
               ул. Летниковская, д. 16
            </div>
         </div>
         <div class="column four wide computer footer-address">
            <div class="ui header">Региональный офис
               в Екатеринбурге
            </div>
            <div class="content">
               ул. Братская, д. 27/3, подъезд 2
            </div>
         </div>
         <div class="column four wide computer sixteen wide tablet contacts-footer">
            <div class="footer-contact-wrap">
               <div class="contacts-wrap">
                  <div class="ui grid">
                     <div class="one wide column"><img src="/images/phone_big.png"  class="phone-icon--big" alt=""></div>
                     <div class="fourteen wide column">
                        <div class="ui header">8 (800) 555-39-86</div>
                        <div class="content">Заказать бесплатный звонок </div>
                     </div>
                  </div>
               </div>
               <div class="ui red fluid button show-modal">Оформить заявку</div>
            </div>
         </div>
      </div>
   </div>
</div>

app/views/shared/_header.html.erb
<div class="ui container">
   <header>
      <div class="top-contacts-wrap">
         <div class="ui stackable two column grid">
            <div class="four wide column">
               <a href="/">
               <img src="/images/logo.png" alt="" class="logo">
               </a>
            </div>
            <div class="twelve wide computer sixteen wide tablet column">
               <div class="ui grid top-contacts">
                  <div class="four wide computer four wide tablet sixteen wide mobile column item">
                     <img src="/images/locate.png" class="contacts-icon" alt="">
                     <span class="span "><a class="contacts-link" href="/contacts/1">Контакты</a></span>
                  </div>
                  <div class="four wide computer four wide tablet sixteen wide mobile column item">
                     8 (800) 555-39-86
                     <div class="sub">
                        <img src="/images/phone.png" alt="" class="contacts-icon">Бесплатно по России
                     </div>
                  </div>
                  <div class="four wide computer four wide tablet sixteen wide mobile column item">
                     8 (495) 212-11-31
                     <div class="sub">
                        <img src="/images/at.png" alt="" class="contacts-icon">info@vira-trade.ru
                     </div>
                  </div>
                  <div class="four wide computer four wide tablet sixteen wide mobile column">
                     <div class="search-input">

                        <%= form_tag("/search", method: "get") do %>
                          <div class="ui icon input">
                             <input type="text" placeholder="Поиск по сайту" name='title'>
                             <i class="search icon"></i>
                          </div>
                        <% end %>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <div class="ui grid menu--top-wrap">
         <div class="computer only row">
            <div class="sixteen wide column">
               <div class="ui red seven item inverted menu menu--top">
                  <% menus = Menu.all %>
                  <% menus.each_with_index do |i, index| %>

                    <% if index + 1 <= 6 %>
                      <a class="item" href="<%= polymorphic_path(i.itemable_type.constantize.find(i.itemable_id)) %>">
                        <%= raw i.title %>
                      </a>
                    <% end %>

                  <% if (index + 1)  == 7 %>
                    <div class="ui dropdown red item more-menu">
                       Еще
                       <i class="angle down icon"></i>
                       <div class="ui red three item inverted menu more-menu-sub">
                  <% end %>

<!--                           <a class="item" style="color: #fff !important">Безопасность</a>
                          <a class="item" style="color: #fff !important">Автоспецтехника</a>
                          <a class="item" style="color: #fff !important">Лизинг</a> -->
                  <% if (index + 1)  > 6 %>
                          <a class="item" style="color: #fff !important" href="<%= polymorphic_path(i.itemable_type.constantize.find(i.itemable_id)) %>">
                            <%= raw i.title %>
                          </a>
                  <% end %>

                  <% if (menus.size - 1) == index %>

                           </div>
                        </div>
                     </div>
                  <% end %>

                  <% end %>
                  <!-- end main loop -->


            </div>
         </div>
      </div>
   </header>
</div>

app/views/shared/_leftside.html.erb
<div class="four wide column computer only">
   <div class="sidebar-left">
      <% SpecItem.all.order(position: :asc).each do |s| %>
        <div class="item">
           <div class="inner">
              <div class="image-container">
                 <img src="<%= s.image.file.url %>" alt="" class="ui image">
                 <div class="after">
                    <div class="content">
                       <div class="head"><%= s.title %></div>
                       <p class="sub_cont">
                          <%= s.desc %>
                       </p>
                       <a href="<%= s.link %>" class="fluid ui red button <%= s.callback == true ? 'show-modal' : '' %>"><%= s.link_text %></a>
                    </div>
                 </div>
              </div>
           </div>
        </div>
      <% end %>
   </div>
</div>

app/views/shared/_mob_header.html.erb
<!--[if IE]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->

<div class="ui one column mobile tablet only grid">
   <div class="column">
      <div class="ui fixed four item white menu mobile-menu-wrap">
         <div class="left menu">
            <div class="item mobile-logo-wrap">
              <a href="/">               <img src="/images/logo.png" alt="" class="ui image mobile-logo"></a>

            </div>
            <div class="item phone-wrap">
               <div class="phone">8 (800) 555-39-86</div>
            </div>
         </div>
         <div class="right menu">
            <div class="item">
               <i class="search icon"></i>
               <a class="mobile-menu-control"><i class="content icon"></i></a>
            </div>
         </div>
      </div>
   </div>
</div>
<div class="ui  segment mobile-search-wrap">
  <%= form_tag("/search", method: "get") do %>
    <div class="ui input">
       <input type="text" placeholder="Поиск по сайту" name='title'>
    </div>
  <% end %>
</div>
<div class="ui right vertical red inverted menu sidebar">
   <div class="side-menu-wrap">
<!--       <a class="active item">
      Люлки
      </a>
      <a class="item">
      Миникраны
      </a>
      <a class="item">
      Удлинители стрел КМУ
      </a>
      <a class="item">
      Захваты
      </a>
      <a class="item">
      Буровое оборудование
      </a>
      <a class="item">
      Запчасти и сервис
      </a> -->
<!--     <% menu_items.each do |i| %>
      <a class="item" href="<%= category_path(i) %>">
        <%= i.title %>
      </a>
    <% end %> -->

    <% Menu.all.each do |i| %>
      <a class="item" href="<%= polymorphic_path(i.itemable_type.constantize.find(i.itemable_id)) %>">
        <%= raw i.title %>
      </a>
    <% end %>
<!--       <a class="item" style="color: #fff !important">Безопасность</a>
      <a class="item" style="color: #fff !important">Автоспецтехника</a>
      <a class="item" style="color: #fff !important">Лизинг</a> -->
   </div>
</div>
<a href="#0" class="cd-top"><i class="angle up icon"></i></a>

app/views/shared/_news_item.html.erb
<div class="news-wrap">
   <div class="ui header news-header">
      <%= raw title %>
      <div class="ui sub header">
         <%= raw date.strftime('%d.%m.%Y') %>
      </div>
   </div>
   <div class="news-content">
      <p style="font-size: 18px; font-weight: 300">
         <%= raw short %>
      </p>
      <p>
      </p>
      <div class="ui grid">
         <div class="mobile only row">
            <div class="sixteen wide column">
               <img src="<%= raw image %>" class="ui image" alt="">
            </div>
         </div>
         <div class="eight wide computer column sixteen wide mobile column">
            <%= raw content %>
         </div>
         <div class="eight wide computer column">
            <img src="<%= image %>" class="ui image computer-only-img" alt="">
         </div>
      </div>
   </div>
</div>

app/views/shared/_prod_item.html.erb
<div class="sixteen wide mobile eight wide tablet four wide computer column">
   <div class="card computer-card">
     <a href="<%= product_path(prod) %>">

        <div class="header--main"><%= prod.title %></div>
        <div class="inner">
           <div class="image product-image-container">
              <img class="ui image" src="<%= prod.pictures.thumb_of_main %>" alt="">
              <div class="after"></div>
           </div>
           <div class="content">
              <div class="header">
                 <div class="ui two column stackable grid main-item-data">
                    <div class="column">
                       <div class="price"><%= prod.price %> руб.</div>
                    </div>
                    <div class="column">
                       <div class="presence"><%= raw presence(prod) %></div>
                    </div>
                 </div>
              </div>
              <div class="description">
                 <%= raw prod.short_desc %>
              </div>
           </div>
        </div>
     </a>
   </div>

   <div class="mobile-card">
     <a href="<%= product_path(prod) %>">

        <div class="ui grid">
           <div class="row">
              <div class="seven wide column">
                 <div class="image product-image-container">
                    <img class="ui image" src="<%= prod.pictures.main_or_first %>" alt="">
                    <div class="after"></div>
                 </div>
              </div>
              <div class="nine wide column">
                 <div class="title"><%= prod.title %></div>
                 <div class="presence presence--true"><%= prod.status == 'aval' ? 'В наличии' : 'Нет в наличии' %></div>
                 <div class="price"><%= prod.price %> руб.</div>
              </div>
           </div>
        </div>
     </a>
   </div>


</div>