config/routes.rb
Rails.application.routes.draw do

  resources :pages
  # resource :service_spare, only: [:show] do
  get '/service_spare/:id', to: 'service_spare#show', as: 'service_spare'
  # end

  get 'search', to: 'search#index'

  get 'search/show', to: 'searche#show'

  resources :news_items
  resources :contacts

  get '/service/:id', to: 'service#show', as: 'service'

  get 'home/index'

  resources :categories, only: [:show], shallow: true do
    resources :products, only: [:show]
  end

  mount Ckeditor::Engine => '/ckeditor'
  root to: 'home#index'

  devise_for :users, controllers: { registrations: "registrations" }

  mount Uploader::Engine => '/uploader'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routinrdmg.html
  # root to: 'home@index'
end

app/models/home.rb
class Home < ApplicationRecord
  has_many :teasers, :as => :assetable, :dependent => :destroy
  fileuploads :teasers

  rails_admin do
    edit do
      field :about, :ck_editor
      field :teasers do
        label { 'Фото для салйдера' }
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @yt = Youtube.all
    @news = NewsItem.all
    @specs = Spec.all
    @home = Home.first
    @products = Product.all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="ui container">
   <div class="slider">
      <div class="owl-carousel owl-slider owl-theme slider-caruseul">

        <% @home.teasers.each do |t| %>
           <div class="slide">
              <div class="image" style="background:url(<%= t.file.url %>)"></div>
              <div class="slide__text">
                 <div class="title"><%= t.slider_desc.upcase %></div>
                 <a href="<%= t.slider_link %>" class="button">Читать далее...</a>
                 <div class="clearfix"></div>
              </div>
              <div class="after"></div>
           </div>
        <% end %>

      </div>
   </div>
</div>
<div class="ui container">
   <div class="specs">
   <div class="ui two column grid">
      <div class="column">
         <h2 class="ui header header--red">СПЕЦПРЕДЛОЖЕНИЯ</h2>
      </div>
      <div class="column">
         <div id="spec_nav" class="right floated"></div>
      </div>
   </div>
<!--       <h2 class="ui header header--red">

      </h2> -->
      <div class="ui stackable three column grid container">
        <div class="owl-carousel specs-carousel">
          <% ids = ['one', 'two', 'third'] %>
          <% @specs.each_with_index do |s, index| %>
               <div class="column main-image-column" id="spec-<%= ids[index] %>">
                  <a href="<%= s.link %>" class="card">
                     <div class="main-image-container" style="background: url(<%= s.image.file.url %>) no-repeat; background-position: center; background-size: cover">
                        <div class="after">
                           <div class="header"><%= s.title %></div>
                           <div class="content"><%= s.desc %></div>
                           <div class="price"><%= s.price %></div>
                        </div>
                     </div>
                  </a>
             </div>
          <% end %>
        </div>


      </div>
   </div>
</div>

<div class="ui container">
  <div class="popular">
      <div class="main-items">
         <h2 class="ui header header--red">
            НАША ПРОДУКЦИЯ
         </h2>

         <% last_item = @products.count - 1 %>


         <% @products.each_with_index do |prod, index| %>

           <% if index ==0  %>
             <div class="ui grid">
           <% end %>

               <% unless index == 8 %>
                   <%= render 'shared/prod_item', prod: prod %>
               <% end %>

           <% if index == 8 %>
             </div>

             <div class="show-more">
                <div class="fluid ui red centered button">
                   Показать еще
                   <i class="angle down icon"></i>
                </div>
             </div>

             <div class="rows--hidden">
                <div class="ui grid">
                   <%= render 'shared/prod_item', prod: prod %>
                    <% if index == last_item %>
                </div>
             </div>


               <% end %>
           <!-- inner if -->
           <% end %>
           <!-- if end -->

         <% end %>

             <div class="close-up">
                <div class="fluid ui red centered button">
                   Свернуть
                   <i class="angle up icon"></i>
                </div>
             </div>

      </div>
  </div>
</div>
</div>
</div>


<!-- </div> -->
<!-- cont -->
<div class="advantages">
   <div class="ui container">
      <h2 class="ui center aligned header header--red">НАШИ ПРЕИМУЩЕСТВА</h2>
      <div class="ui four column doubling grid">
         <div class="column">
            <div class="advantages-item">
               <div class="img-wrap">
                  <img src="images/a1.png" alt="" class="ui centered image">
               </div>
               <div class="content">
                  Высокое качество<br>продукции
               </div>
            </div>
         </div>
         <div class="column">
            <div class="advantages-item">
               <div class="img-wrap">
                  <img src="images/a2.png" alt="" class="ui centered image">
               </div>
               <div class="content">
                  Индивидуальный
                  подход<br>к клиенту
               </div>
            </div>
         </div>
         <div class="column">
            <div class="advantages-item">
               <div class="img-wrap">
                  <img src="images/a3.png" alt="" class="ui centered image">
               </div>
               <div class="content">
                  Постоянным<br>
                  клиентам скидки!
               </div>
            </div>
         </div>
         <div class="column">
            <div class="advantages-item">
               <div class="img-wrap">
                  <img src="images/a4.png" alt="" class="ui centered image">
               </div>
               <div class="content">
                  Техническая поддержка<br>
                  24 часа в сутки
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
<div class="about-wrap">
   <div class="ui container">
      <div class="about">
         <h2 class="ui header header--red">
            О КОМПАНИИ
         </h2>
         <div class="content">
            <div class="ui grid">
               <div class="six wide computer sixteen wide mobile column">
                  <img src="images/about.png" alt="" class="ui image">
               </div>
               <div class="ten wide computer sixteen wide mobile column">
                  <p class="first">«Вира-Трейд»  компания, предоставляющая полный комплекс услуг по производству, поставке и ремонту спецавтотехники.</p>
                  <h3 class="ui header">Услуги</h3>
                  <p>Компания «Вира-Трейд» осуществляет поставку и обслуживание техники на всей территории РФ, работает с такими крупными заказчиками как: «Сургутнефтегаз», «Роснефть», «Лукойл», «СтройГазКонсалтинг», а также предприятиями энергетического комплекса Северо-Западного, Центрального, Приволжского и Уральского региона.</p>
                  <h3 class="ui header">Опыт</h3>
                  <p>Наши сотрудники имеют огромный опыт в области производства и реализации спецавтотехники таких производителей как: Oil&Steel, КАМАЗ, ГАЗ, Урал, Нефаз, Hyundai,MAN, Hino, Fusso, МАЗ,  «Ивановская марка», Челябинец, Галичанин, Fassi, Hiab, Palfinger, PM, что позволяет предоставить заказчику информацию о том товаре, который наилучшим образом подойдёт для выполнения поставленных задач.</p>
                  <h3 class="ui header">Качество обслуживания</h3>
                  <p>Компания «Вира-Трейд» постоянно развивает творческий и интеллектуальный потенциал, наращивает техническую и производственную базы. Выверенный алгоритм проектирования и производства позволяет специалистам Компании решать практически любые задачи в четком взаимодействии с Заказчиком.</p>
                  <p>
                     <a href="#" class="link--red">Читать еще...</a>
                  </p>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>

<div class="ui container">
   <div class="news">
      <div class="ui two column grid">
         <div class="column">
            <h2 class="ui header header--red"> НОВОСТИ </h2>
         </div>
         <div class="column">
            <div id="news_nav" class="right floated"></div>
         </div>
      </div>
      <div class="owl-carousel news-carousel">
        <% if @news.present? %>
          <% @news.each do |n| %>
          <a href="<%= news_item_path(n) %>" class="news-item">
             <div class="item ">
                <img src="<%= n.simple_picture.file.url %>" alt="">
                <div class="slide-meta">
                   <div class="slide-date"><%= n.created_at.strftime('%d.%m.%Y') %></div>
                   <div class="slide-desc"><%= n.title %></div>
                </div>
             </div>
            <% end %>
          </a>
        <% end %>

      </div>
   </div>
</div>
<div class="ui container">
   <div class="youtube">
      <div class="ui two column grid">
         <div class="column">
            <h2 class="ui header header--red"> МЫ НА YOUTUBE </h2>
         </div>
         <div class="column">
            <div id="youtube_nav" class="right floated"></div>
         </div>
      </div>
      <% if @yt.present? %>
        <div class="owl-carousel youtube-carousel">
           <% @yt.each do |y| %>
           <div class="item">

<!--            <object style="width:100%;height:100%;width: 270px; height: 180.25px; float: none; clear: both; margin: 2px auto;" data="<%= raw y.link %>">
              </object> -->
              <div class="youtube-player" data-id="<%= raw y.link.split('=').last %>"></div>
              <div class="slide-meta">
                 <div class="slide-desc"><%= y.desc %></div>
              </div>
           </div>
           <% end %>
        </div>
      <% end %>
   </div>
</div>
<div class="partners-wrap">
   <div class="ui container">
      <div class="partners">
         <div class="ui two column grid">
            <div class="column">
               <h2 class="ui header header--red">НАШИ ПАРТНЕРЫ</h2>
            </div>
            <div class="column">
               <div id="partners_nav" class="right floated"></div>
            </div>
         </div>
         <div class="owl-carousel partners-carousel">
        <% if Partner.all.present? %>
           <% Partner.all.each do |p| %>
              <a href="#">
                <div class="item"><img src="<%= p.image.file.url %>" alt=""></div>
              </a>
           <% end %>
        <% end %>
         </div>
      </div>
   </div>
</div>